<a href="https://colab.research.google.com/github/Kristina140699/AndroidWork/blob/main/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Arrays
## Single Dimensional Array

In [ ]:
import numpy as np
n1 = np.array([10, 20, 30, 40, 50])
n1

array([10, 20, 30, 40, 50])

In [ ]:
type(n1)

numpy.ndarray

## Multi Dimensional Array

In [ ]:
n2 = np.array([[1,2,3,4,5],[11, 12, 13, 14, 15],[10, 20, 30, 40, 50]])
n2

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [10, 20, 30, 40, 50]])

In [ ]:
type(n2)

numpy.ndarray

## Zero Arrays

In [ ]:
n0 = np.zeros((5,2))
n0

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Numpy array with same number

In [ ]:
n4 = np.full((2,3), 14)
n4

array([[14, 14, 14],
       [14, 14, 14]])

## Numpy array within a range

In [ ]:
n5 = np.arange(10, 20) #this prints all the numbers including 10 and excluding 20
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
n5 = np.arange(15, 65, 5) # here 5 is the step/ interval after which the numbers will be printed.
n5

array([15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

## Numpy array with random numbers

In [ ]:
n6 = np.random.randint(50, 250, 5)
n6

array([125, 209, 106, 188, 236])

## Shape of Numpy array

In [ ]:
n7 = np.array([[1,2,3], [4,5,6]])
n7

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
n7.shape

(2, 3)

In [ ]:
n7.shape = (3, 2)
n7

array([[1, 2],
       [3, 4],
       [5, 6]])

# Joining Numpy Arrays

## Stacking


1.   vSatck(): vertically stack the arrays. One on top of the another.
2.   hStack(): horizontally stack the arrays. One after the another.
3.   column_stack(): stacks each array column wise.




In [ ]:
import numpy as np

In [ ]:
n1 = np.array([10, 20, 30])
n2 = np.array([40, 50, 60])

np.vstack((n1, n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
n1 = np.array([11, 12, 13])
n2 = np.array([14,15, 16])

np.hstack((n1, n2))

array([11, 12, 13, 14, 15, 16])

In [ ]:
n1 = np.array([1, 2, 3, 4])
n2 = np.array([5, 6, 7, 8])

np.column_stack((n1, n2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Numpy Intersection & Difference
## Interection:
Finds the common elements between the arrays.

## Difference:
Finds the elements that are available on the first array and not available in the second array.

In [ ]:
import numpy as np

In [ ]:
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90])

In [ ]:
np.intersect1d(n1, n2)

array([50, 60])

In [ ]:
np.setdiff1d(n1, n2)

array([10, 20, 30, 40])

In [ ]:
np.setdiff1d(n2, n1)

array([70, 80, 90])

# Numpy Array Mathematics


1.   Addition
2.   Subtraction
3.   Multiplication




In [ ]:
n1 = np.array([10, 20, 30, 40, 50])
n2 = np.array([60, 70, 80, 90, 100])

np.sum([n1, n2])

550

In [ ]:
np.sum([n1,n2], axis=0) #adds up vertically

array([ 70,  90, 110, 130, 150])

In [ ]:
np.sum([n1,n2], axis=1) #adds up horizontally, elements within the same array

array([150, 400])

## Scaler Arithmetics

In [ ]:
n1 = np.array([10, 20, 30, 40, 50])

In [ ]:
n1+1

array([11, 21, 31, 41, 51])

In [ ]:
n1*2

array([ 20,  40,  60,  80, 100])

In [ ]:
n1-3

array([ 7, 17, 27, 37, 47])

In [ ]:
n1/10

array([1., 2., 3., 4., 5.])

## Math Functions

1. mean() - mean
2. std() - standard deviation
3. median() - median

In [ ]:
n1 = np.array([10, 14, 23, 64, 78, 48, 62, 31])

In [ ]:
np.mean(n1)

41.25

In [ ]:
np.std(n1)

23.72103496898902

In [ ]:
np.median(n1)

39.5

## Saving and Loading Numpy Array

We can save the numpy arrays with any name of our choice and load it back with the object_name.npy.

In [20]:
import numpy as np  #saving numpy array

n1 = np.array([10, 20, 30, 40, 50, 60])
np.save('numpy1', n1)

In [ ]:
n2 = np.load('numpy1.npy')  #loading numpy array
n2

array([10, 20, 30, 40, 50, 60])

## Numpy Broad casting

For broadcating to happen one of the following conditions needs to be satisfied.

1. Dimensions must be same. Dimensions of both the arrays must be same.

2. When the dimensions are not same we'll add trailing 1s to the shorter array. If this condition meets then we can broadcast across the other array.

In [ ]:
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([70, 80, 90,])

# n1+n2 #This will give and  error!
# operands could not be broadcast together with shapes (6,) (3,)

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

In [21]:
n1 = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
n2 = np.array([10, 20, 30])

In [22]:
n1.shape, n2.shape

((3, 3), (3,))

In [23]:
n1+n2

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [24]:
n1 = np.array([1,2,3])
n1.shape = (3,1)
n1

array([[1],
       [2],
       [3]])

In [25]:
n2 = np.array([4,5,6])
n2.shape = (1,3)
n2

array([[4, 5, 6]])

In [26]:
n1+n2

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

## Numpy Matrices

In [30]:
n1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
n1[0] # accessing the rows

array([1, 2, 3])

In [33]:
n1[1]

array([4, 5, 6])

In [32]:
n1[:, 2] # accessing the columns

array([3, 6, 9])

In [34]:
n1[1,1]

5

In [35]:
n1[2,2]

9

## Transporse of a Matrix

In [36]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
n1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Numpy Matrix Multiplication

In [38]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
n2 = np.array([[4,5,6], [9, 8, 7], [1, 0, 9]])
n2

array([[4, 5, 6],
       [9, 8, 7],
       [1, 0, 9]])

## n1.dot(n2) != n2.dot(n1)

In [40]:
n1.dot(n2)

array([[ 25,  21,  47],
       [ 67,  60, 113],
       [109,  99, 179]])

In [41]:
n2.dot(n1)

array([[ 66,  81,  96],
       [ 90, 114, 138],
       [ 64,  74,  84]])